README.md
src/main/scala/io/citrine/lolo/learners/RandomForest.scala
src/test/scala/io/citrine/lolo/learners/RandomForestTest.scala

Adding wrappers around common ML methods

---

README.md
pom.xml
src/test/scala/io/citrine/lolo/learners/RandomForestTest.scala

This should let us get on the central repository.  I feel like Hermes.

Adding deployment info to pom

---

README.md
pom.xml
src/main/scala/io/citrine/lolo/learners/RandomForest.scala
src/test/scala/io/citrine/lolo/learners/RandomForestTest.scala

Includes central repo deployment and a random forest convenience wrapper.

Release 0.2.0

---

src/test/scala/io/citrine/lolo/trees/classification/ClassificationTreeTest.scala

Looks just like the test for more classes
CC: @sparadiso

Adding a test for binary classification

---

src/main/scala/io/citrine/lolo/trees/splits/ClassificationSplitter.scala
src/main/scala/io/citrine/lolo/trees/splits/RegressionSplitter.scala
src/main/scala/io/citrine/lolo/trees/splits/Split.scala

This will save memory.
CC: @sparadiso @eantono

Base categorical splits on bitset

---

src/main/scala/io/citrine/lolo/linear/LinearRegression.scala
src/main/scala/io/citrine/lolo/trees/regression/RegressionTrainingLeaf.scala
src/main/scala/io/citrine/lolo/trees/regression/RegressionTrainingNode.scala
src/test/scala/io/citrine/lolo/trees/regression/RegressionTreeTest.scala

This is a prototype in response to #69 
@eantono do you have a good case for tests?

Bubbling leaf importance up through tree

---

src/main/scala/io/citrine/lolo/bags/Bagger.scala

This should reduce the peak memory usage during training.
CC: @eantono @sparadiso

Refactor the training to discard each model's meta-data asap

---

README.md
pom.xml

Performance improvements by updating the `netlib-blas` version.

Release 0.2.6

---

README.md
pom.xml

Version bump

---

src/main/scala/io/citrine/lolo/linear/LinearRegression.scala
src/test/scala/io/citrine/lolo/linear/LinearRegressionTest.scala
src/test/scala/io/citrine/lolo/trees/regression/RegressionTreeTest.scala

Categorical values were being dropped from the feature importance.

Adding tests to expose bug in linear model feature importance

---

src/main/scala/io/citrine/lolo/trees/regression/RegressionTrainingLeaf.scala

In case the impurity is a small amplitude negative number, round up to zero.

Differences of small numbers have noise

---

src/main/scala/io/citrine/lolo/trees/classification/ClassificationTree.scala
src/main/scala/io/citrine/lolo/trees/regression/RegressionTree.scala
src/test/scala/io/citrine/lolo/trees/regression/RegressionTreeTest.scala

Set `maxDepth` properly and check that it is obeyed (it is not)

---

src/main/scala/io/citrine/lolo/util/Async.scala

Adding 1 ms yield to canStop

---

pom.xml
src/test/scala/io/citrine/lolo/PerformanceTest.scala
src/test/scala/io/citrine/lolo/stats/correlations/DistanceCorrelationTest.scala

Changes to prevent spurious test failures on travis.  No changes to the main source; just tests.

Feature: improved performance testing stability

---

src/main/scala/io/citrine/lolo/bags/Bagger.scala
src/main/scala/io/citrine/lolo/linear/LinearRegression.scala
src/main/scala/io/citrine/lolo/trees/classification/ClassificationTree.scala
src/main/scala/io/citrine/lolo/trees/regression/RegressionTree.scala

Improved usage in decision trees, linear regression, and the bagger.

Feature: consistent use of hyperparameters

---

src/main/scala/io/citrine/lolo/Learner.scala
src/main/scala/io/citrine/lolo/bags/Bagger.scala
src/main/scala/io/citrine/lolo/learners/RandomForest.scala
src/main/scala/io/citrine/lolo/linear/GuessTheMean.scala
src/main/scala/io/citrine/lolo/linear/LinearRegression.scala
src/main/scala/io/citrine/lolo/transformers/Standardizer.scala
src/main/scala/io/citrine/lolo/trees/classification/ClassificationTree.scala
src/main/scala/io/citrine/lolo/trees/regression/RegressionTree.scala

This way one were to set a hyperparameter in, say, a leaf learner,
it would be gotten by getHypers called on the parent

Access hypers through a getter, which can pull hypers from internal learners

---

pom.xml
src/main/scala/io/citrine/lolo/bags/Bagger.scala
src/test/scala/io/citrine/lolo/bags/BaggerTest.scala

Missed a hypers reference

---

src/main/scala/io/citrine/lolo/MultiTaskLearner.scala
src/main/scala/io/citrine/lolo/bags/MultiTaskBagger.scala
src/main/scala/io/citrine/lolo/stats/metrics/ClassificationMetrics.scala
src/main/scala/io/citrine/lolo/trees/multitask/MultiTaskTrainingNode.scala
src/main/scala/io/citrine/lolo/trees/multitask/MultiTaskTree.scala
src/main/scala/io/citrine/lolo/trees/splits/MultiTaskSplitter.scala
src/test/scala/io/citrine/lolo/PerformanceTest.scala
src/test/scala/io/citrine/lolo/bags/MultiTaskBaggerTest.scala
src/test/scala/io/citrine/lolo/trees/multitask/MultiTaskTreeTest.scala
src/test/scala/io/citrine/lolo/trees/splits/MultiTaskSplitterTest.scala

Adding multitask learners with a first implementation of multitask trees.  A multitask learner emits multiple training results, at which point it follows the same pattern as a single task learner.

Feature: MultiTaskTrees

---

src/main/scala/io/citrine/lolo/transformers/Standardizer.scala
src/test/scala/io/citrine/lolo/transformers/StandardizerTest.scala

Just like single task, but with multiple output transformers

Feature: multitask standardizer

---

src/main/scala/io/citrine/lolo/trees/impurity/GiniCalculator.scala
src/main/scala/io/citrine/lolo/trees/impurity/ImpurityCalculator.scala
src/main/scala/io/citrine/lolo/trees/impurity/MultiImpurityCalculator.scala
src/main/scala/io/citrine/lolo/trees/impurity/VarianceCalculator.scala
src/main/scala/io/citrine/lolo/trees/splits/ClassificationSplitter.scala
src/main/scala/io/citrine/lolo/trees/splits/MultiTaskSplitter.scala
src/main/scala/io/citrine/lolo/trees/splits/RegressionSplitter.scala
src/test/scala/io/citrine/lolo/trees/impurity/MultiImpurityCalculatorTest.scala
src/test/scala/io/citrine/lolo/trees/splits/MultiTaskSplitterTest.scala
src/test/scala/io/citrine/lolo/trees/splits/SplitterTest.scala

Clean up multitask

---

pom.xml
src/main/scala/io/citrine/lolo/bags/Bagger.scala
src/main/scala/io/citrine/lolo/bags/MultiTaskBagger.scala
src/main/scala/io/citrine/lolo/trees/impurity/VarianceCalculator.scala
src/test/scala/io/citrine/lolo/bags/MultiTaskBaggerTest.scala
src/test/scala/io/citrine/lolo/trees/impurity/GiniCalculatorTest.scala
src/test/scala/io/citrine/lolo/trees/impurity/VarianceCalculatorTest.scala

Resync develop

---

pom.xml
src/test/scala/io/citrine/lolo/PerformanceTest.scala
src/test/scala/io/citrine/lolo/bags/MultiTaskBaggerTest.scala
src/test/scala/io/citrine/lolo/trees/splits/ClassificationSplitterTest.scala

What a difference a data structure makes!  Classification trees are now up to 6x faster.

Release 0.4.2: Improved classification performance

---

pom.xml

Also de-duping the scala maven plugins.

Update dependencies to use scala 2.12

---

pom.xml

I believe this bug was causing tests to not run in travis

Move the scala-maven-plugin out of build-extras

---

pom.xml

Just getting the version bump back.

Resync 1.0.2

---

pom.xml

Add lolopy profile and create an uber-jar

---

pom.xml
python/lolopy/version.py
src/main/scala/io/citrine/lolo/bags/Bagger.scala
src/test/scala/io/citrine/lolo/bags/BaggerTest.scala

Resync develop with hotpatch

---

python/lolopy/learners.py
python/lolopy/metrics.py
python/lolopy/tests/test_learners.py
python/lolopy/tests/test_metrics.py
python/lolopy/utils.py
src/main/scala/io/citrine/lolo/learners/RandomForest.scala
src/main/scala/io/citrine/lolo/trees/regression/RegressionTree.scala
src/main/scala/io/citrine/lolo/util/LoloPyDataLoader.scala
src/test/scala/io/citrine/lolo/util/LoloPyDataLoaderTest.scala

Adds the ability to use Lolo merits from lolopy
I had to add a new utility interface to lolo to allow for making a PredictionResult from Python data. So, we will need to up the version of the lolo package when we eventually sync develop with master.
I am sending this PR now so that I can use Travis.

Added merits/metrics and more learners to lolopy

---

python/lolopy/learners.py
python/lolopy/loloserver.py
python/lolopy/tests/test_learners.py
src/main/scala/io/citrine/lolo/learners/RandomForest.scala

This fixes the bug observed when testing the bias learner. I made the random forest in that test fit to the data less strongly, which should make the bias learner more effective. 
I also made some minor changes to the RF docs

Fixed test bug, and polished RF docs

---

python/README.md
python/lolopy/loloserver.py
python/lolopy/tests/test_server.py

Adds the ability to set the heap size for the lolo JVM.

Add Ability to Set Heap Size

---

pom.xml
python/lolopy/version.py

Parallel version bumps for Lolo and Lolopy.

Release/2.2.2 -> Master

---

src/main/scala/io/citrine/lolo/bags/Bagger.scala

Actual requirement and message text were in disagreement, causing confusion 
Fixes #174

Fix bug in requirement on minimum number of training samples

---

README.md

Bump version in README.

---

src/main/scala/io/citrine/lolo/bags/BaggedResult.scala

The bias correction terms in Wager et. al. (2014) [1] (equations 7 and 8) are slightly incorrect. They have factors of `n` that should be `n-1`.
The infinitesimal jackknife (IJ) bias term is derived in section 4.1 of [1]. Just before equation 11, they state `Var[N_{bi}] = 1`, where `N_{bi}` is the number of times training point `i` appears in bag `b`. `N_{bi}` follows a multinomial distribution with probabilities `p_i = 1/n` and `n` draws. The variance of this quantity is `(n-1)/n`, not 1, which is why their final result is missing a factor of `(n-1)/n`. This mistake is also caught in Appendix A.2 of [2], in which the authors re-derive the IJ equations for their own edification. See the section after equation A.4, in particular.
The Jackknife after Bootstrap bias term is derived in …

introduce factor of (n-1)/n in jackknife bias correction terms

---

src/main/scala/io/citrine/lolo/trees/Nodes.scala
src/main/scala/io/citrine/lolo/trees/classification/ClassificationTrainingNode.scala
src/main/scala/io/citrine/lolo/trees/classification/ClassificationTree.scala
src/main/scala/io/citrine/lolo/trees/multitask/MultiTaskTrainingNode.scala
src/main/scala/io/citrine/lolo/trees/multitask/MultiTaskTree.scala
src/main/scala/io/citrine/lolo/trees/regression/RegressionTrainingLeaf.scala
src/main/scala/io/citrine/lolo/trees/regression/RegressionTrainingNode.scala
src/main/scala/io/citrine/lolo/trees/regression/RegressionTree.scala
src/main/scala/io/citrine/lolo/trees/splits/ClassificationSplitter.scala
src/main/scala/io/citrine/lolo/trees/splits/MultiTaskSplitter.scala
src/main/scala/io/citrine/lolo/trees/splits/RegressionSplitter.scala
src/main/scala/io/citrine/lolo/trees/splits/Splitter.scala
src/test/scala/io/citrine/lolo/trees/multitask/MultiTaskTreeTest.scala
src/test/scala/io/citrine/lolo/trees/splits/MultiTaskSplitterTest.scala
src/test/scala/io/citrine/lolo/trees/splits/SplitterTest.scala

PLA-8567
Implement `getFeatureImportance` for multitask model.

Multitask feature importance

---

src/main/scala/io/citrine/lolo/validation/Merit.scala
src/test/scala/io/citrine/lolo/validation/CalibrationStudy.scala
src/test/scala/io/citrine/lolo/validation/MeritTest.scala

Reverts CitrineInformatics/lolo#266

Revert "Allow observational option for more Merits"

---

src/main/scala/io/citrine/lolo/validation/Merit.scala
src/test/scala/io/citrine/lolo/validation/CalibrationStudy.scala
src/test/scala/io/citrine/lolo/validation/MeritTest.scala

Reverts CitrineInformatics/lolo#268

Revert "Revert "Allow observational option for more Merits""

---

.travis.yml
build.sbt
project/Dependencies.scala
src/test/scala/io/citrine/lolo/trees/regression/RegressionTreeTest.scala

The change here causes our test runner to log each test it runs, which I am hoping will alleviate the travis timeout issue.
There is also one test that had about a 5% failure rate. I changed a param to alleviate that.

Trying to improve Travis build stability

---

build.sbt
project/Dependencies.scala
src/test/scala/io/citrine/lolo/AccuracyTest.scala
src/test/scala/io/citrine/lolo/PerformanceTest.scala
src/test/scala/io/citrine/lolo/TestUtils.scala
src/test/scala/io/citrine/lolo/bags/BaggedResultTest.scala
src/test/scala/io/citrine/lolo/bags/BaggerTest.scala
src/test/scala/io/citrine/lolo/bags/MultiTaskBaggerTest.scala
src/test/scala/io/citrine/lolo/learners/ExtraRandomTreesTest.scala
src/test/scala/io/citrine/lolo/learners/RandomForestTest.scala
src/test/scala/io/citrine/lolo/linear/LinearRegressionTest.scala
src/test/scala/io/citrine/lolo/stats/correlations/DistanceCorrelationTest.scala
src/test/scala/io/citrine/lolo/stats/metrics/ClassificationMetricsTest.scala
src/test/scala/io/citrine/lolo/transformers/FeatureRotatorTest.scala
src/test/scala/io/citrine/lolo/transformers/StandardizerTest.scala
src/test/scala/io/citrine/lolo/trees/FeaturePowerSetTermsTest.scala
src/test/scala/io/citrine/lolo/trees/classification/ClassificationTreeTest.scala
src/test/scala/io/citrine/lolo/trees/multitask/MultiTaskTreeTest.scala
src/test/scala/io/citrine/lolo/trees/regression/RegressionTreeTest.scala
src/test/scala/io/citrine/lolo/trees/splits/BoltzmannSplitterTest.scala
src/test/scala/io/citrine/lolo/trees/splits/ClassificationSplitterTest.scala
src/test/scala/io/citrine/lolo/trees/splits/ExtraRandomRegressionSplitterTest.scala
src/test/scala/io/citrine/lolo/trees/splits/MultiTaskSplitterTest.scala
src/test/scala/io/citrine/lolo/trees/splits/SplitterTest.scala
src/test/scala/io/citrine/lolo/validation/CalibrationStudy.scala
src/test/scala/io/citrine/lolo/validation/CrossValidationTest.scala
src/test/scala/io/citrine/lolo/validation/MeritTest.scala
src/test/scala/io/citrine/lolo/validation/StatisticalValidationTest.scala

The other issue I've noticed build failures were just random flakes. I whipped up a seed random scheme for the test suite this morning to try to fix that. 
The one thing I recognize is that this `SeedRandomMixin` is not currently using a splittable RNG, although I don't know if we care about that for the test suite.

SeedRandom for test suite

---

src/main/scala/io/citrine/lolo/linear/MultiTaskLinearRegression.scala
src/test/scala/io/citrine/lolo/bags/MultiTaskBaggerTest.scala
src/test/scala/io/citrine/lolo/linear/MultiTaskLinearRegressionTest.scala

Adds a multi-task linear regression learner that trains independent single-task learners on each label.

PLA-10549: Multi-task linear regression

---

python/examples/profile/scaling-test.ipynb
python/lolopy/learners.py
src/main/scala/io/citrine/lolo/util/LoloPyDataLoader.scala

Some minor edits and formatting before I cut a new Lolo and Lolopy release.

Clean up some Lolopy stuff before release

---

src/main/scala/io/citrine/lolo/bags/BaggedModel.scala
src/main/scala/io/citrine/lolo/bags/BaggedTrainingResult.scala
src/main/scala/io/citrine/lolo/bags/Bagger.scala
src/main/scala/io/citrine/lolo/bags/BaggerHelper.scala
src/main/scala/io/citrine/lolo/bags/MultiTaskBagger.scala

If you want to verify this works, pull this branch and `sbt publishLocal` to test out in Mithril before we merge.

Store regular Seq and cast to Par during training/transform only

---

src/main/scala/io/citrine/lolo/bags/BaggedTrainingError.scala
src/main/scala/io/citrine/lolo/bags/Bagger.scala
src/main/scala/io/citrine/lolo/bags/MultiTaskBagger.scala

Having structured error messages here will help us catch the issue and return more actionable messages to users

Create error types for not enough data

---

project/Dependencies.scala

Bump single dep

---

.github/workflows/deployPyPi.yml

There was an issue with the github action to deploy to pypi.

PNE-6628/fix-lolopy-deploy
