pom.xml, src/main/scala/io/citrine/lolo/transformers/Standardizer.scala, src/test/scala/io/citrine/lolo/transformers/StandardizerTest.scala
Standardizes any continuous input features or output labels by giving them zero mean and unit variance.
CC: @sparadiso the logic is all here, but I'm still adding tests.  Please review but don't merge.
=> Adding standardizing meta-learner

pom.xml, src/main/scala/io/citrine/lolo/transformers/Standardizer.scala, src/test/scala/io/citrine/lolo/transformers/StandardizerTest.scala
The standardizer wasn't passing the weights through, which was really important to the functioning of bagged models.
=> Hotfix - standardizer was incorrect

src/main/scala/io/citrine/lolo/bags/Bagger.scala, src/main/scala/io/citrine/lolo/util/Async.scala, src/main/scala/io/citrine/lolo/util/InterruptibleExecutionContext.scala, src/test/scala/io/citrine/lolo/bags/BaggerTest.scala
Bagger training can take a long time.  If its in a webservice, that can cause problems.  We should be able to interrupt it if we need to.
This PR establishes two patterns for making routines interruptible:
* Interruptible parallel collections via the `InterruptibleExecutionContext`
* Consistent thread status checking with `Async.canStop`
The unit test can only make sure the `train` method is interrupted _somewhere_.  I welcome suggestions for checking how quickly it stops running.
CC: @sparadiso
=> Interruptible bagger training

pom.xml
Here's the performance test before:
```
Train,      Apply,      N,      K,      B
0.6287,     1.3247,   1024,      8,    512
1.2826,     2.4847,   1024,      8,   1024
2.7816,     5.2117,   1024,      8,   2048
0.9222,     1.1737,   1024,     16,    512
1.5393,     1.2708,   1024,     32,    512
1.3419,     4.6968,   2048,      8,    512
3.4380,    18.2644,   4096,      8,    512
```
and after:
```
Train,      Apply,      N,      K,      B
0.6724,     0.4315,   1024,      8,    512
1.1610,     0.8089,   1024,      8,   1024
2.6693,     1.5454,   1024,      8,   2048
0.9332,     0.4519,   1024,     16,    512
1.4455,     0.4929,   1024,     32,    512
1.3272,     1.3497,   2048,      8,    512
3.0903,     5.2056,   4096,      8,    512
```
So a bit better than 3x.  CC: @sparadiso @eantono
=> Use a newer version of netlib-blas

src/main/scala/io/citrine/lolo/linear/LinearRegression.scala
The pseudo-inverse is always a safe choice.
=> Hotfix: system blas can be pickier about inversion.

src/main/scala/io/citrine/lolo/trees/regression/RegressionTrainingLeaf.scala, src/test/scala/io/citrine/lolo/trees/regression/RegressionTreeTest.scala
The local variance computation, which is used to weight the importance,
has a weights-related bug that results in negative importance.
CC: @jling11
=> Fix bug in leaf importance calculation

pom.xml, src/test/scala/io/citrine/lolo/PerformanceTest.scala
Re-enabling the performance test and re-basing it on the [theta](https://github.com/CitrineInformatics/theta) performance analysis tool.
=> Moving timings to the theta library

src/main/scala/io/citrine/lolo/trees/splits/ClassificationSplitter.scala, src/main/scala/io/citrine/lolo/trees/splits/RegressionSplitter.scala, src/test/scala/io/citrine/lolo/PerformanceTest.scala, src/test/scala/io/citrine/lolo/trees/splits/SplitterTest.scala
The "is this feature value larger than the last one" logic had an absolute, not relative scale, so large feature values might have been mistakenly labeled as distinct.
=> Hotfix: duplicate inputs

pom.xml, src/main/scala/io/citrine/lolo/util/Async.scala, src/test/scala/io/citrine/lolo/PerformanceTest.scala
I suspect this is causing a significant performance degradation.
=> Removing or altering the sleep (used to yield) in Async.canWait

src/main/scala/io/citrine/lolo/bags/Bagger.scala, src/main/scala/io/citrine/lolo/stats/functions/Friedman.scala, src/test/scala/io/citrine/lolo/TestUtils.scala, src/test/scala/io/citrine/lolo/bags/BaggerTest.scala
The change in the bias calculation is minor; it didn't have a large affect but is motivated by the observation that the uncertainty in this PvA calculation is underestimated with the same ratio as the error (due to getting the exact correct answer when the training row is included).
The major addition is a test of uncertainty calibration, which is re-assuring.
=> Making a small adjustment to uncertainty calculations; adding test

pom.xml, src/main/scala/io/citrine/lolo/bags/Bagger.scala, src/main/scala/io/citrine/lolo/bags/MultiTaskBagger.scala, src/main/scala/io/citrine/lolo/trees/impurity/VarianceCalculator.scala, src/test/scala/io/citrine/lolo/bags/MultiTaskBaggerTest.scala, src/test/scala/io/citrine/lolo/trees/impurity/GiniCalculatorTest.scala, src/test/scala/io/citrine/lolo/trees/impurity/VarianceCalculatorTest.scala
There are a number of bugs:
- Sparse regression labels are causing the `VarianceCalculator.build` method to fail on reduce on empty lists
- The `getLoss` on a multi-bagger produced classification task fails on matching null
- The `biasTraining` generated for sparse regression had NaN where there was a missing label
Fixes:
- Replace `reduce` with `fold` in `VarianceCalculator.build`
- Ignore any `null` or `NaN` actual labels in `BaggerTrainingResult.getPredictedVsActual`
- Ignore any `null` or `NaN` in actual labels when computing `biasTraining`
=> Hotfixes for multi-task

src/main/scala/io/citrine/lolo/trees/impurity/GiniCalculator.scala, src/test/scala/io/citrine/lolo/PerformanceTest.scala, src/test/scala/io/citrine/lolo/trees/splits/ClassificationSplitterTest.scala
We noticed that classification was much slower than regression, which was confusing because those classification examples didn't include jackknife or explicit bias.  Profiling the tests here indicated that the issue was in the `GiniCalculator`, which computes the Gini impurity in a streaming way.  That calculation is much more complicated than the `VarianceCalculator`, and was the source of the performance difference.
The remedy is to replace the `Map[Char, Double]` used to store the class weights with `Array[Double]`, which has much better performance.  The array is sized based on the maximum classification label that is in scope.  Because the encoder emits the lowest possible labels, we expect this to be reasonably efficient.  The only significant losses will occur when computing splits …
=> Classification performance improvements

README.md, pom.xml
Update from scala 2.11 to 2.12.  This is not a binary compatible change, so bump the major version number.
=> Release: 1.0.0

README.md, pom.xml, src/main/scala/io/citrine/lolo/linear/LinearRegression.scala, src/main/scala/io/citrine/lolo/transformers/Standardizer.scala, src/test/scala/io/citrine/lolo/transformers/StandardizerTest.scala
The unregularized linear regression problem is ill posed if there are constant features.  This change skips constant features if there is no regularization (just like we skip NaN and non-real features).
=> Bugfix: drop constant features in linear models

pom.xml
The idea is to generate an uber (fat/shaded/..) jar during packaging and attach it to maven reactor goal so that it is uploaded to central.
Also, minor version bump due to changes.
Generating and deploying the artifacts would work out of the box when profile is activated. (i. e `mvn clean deploy -Plolopy`)
=> Added uber jar profile to pom.xml with shade plugin conf.

cd/before-deploy.sh, cd/deploy.sh
This will deploy the jar-with-dependencies next to the normal jar.
It also cleans up the deploy process to use some newer travis
config options.
=> Enable lolopy profile on deploy

pom.xml, python/lolopy/version.py, src/main/scala/io/citrine/lolo/bags/Bagger.scala, src/test/scala/io/citrine/lolo/bags/BaggerTest.scala
Zero predicted uncertainty is an error state; the uncertainty
might be small but it should always be finite.
=> Adding strict test that uncertainty should be positive

src/main/scala/io/citrine/lolo/bags/BaggedResult.scala, src/main/scala/io/citrine/lolo/bags/Bagger.scala, src/test/scala/io/citrine/lolo/bags/BaggerTest.scala
When there are no bags in the ensemble that have zero instances
of any particularly training row, the jackknife-after-bootstrap
breaks for lack of an out-of-bag estimate.  We protect against this
in two ways:
* In the Bagger, re-drawing the bootstrap until each training
instance is missing from at least one bag
* In the BaggedSingleResult, ignoring jackknife-after-bootstrap
and only using infinitesimal jackknife if there are no
out-of-bag predictions
=> Adding a test that fails for small forests with a bias learner

python/lolopy/learners.py, src/main/scala/io/citrine/lolo/learners/RandomForest.scala
Also changing the default number of features used at each split,
i.e. the "auto" strategy, to use all of them, which is consistent
with sklearn's default.  Also add support for the log2 strategy,
another option in sklearn.
I opted to skip adding new tests because these patterns are already tested: this isn't the first integer or boolean option available in the RandomForest learner in either scala or python.
=> Adding maxDepth and uncertaintyCalibration to RandomForest builder

python/lolopy/learners.py, src/main/scala/io/citrine/lolo/learners/RandomForest.scala, src/main/scala/io/citrine/lolo/trees/classification/ClassificationTrainingNode.scala, src/main/scala/io/citrine/lolo/trees/classification/ClassificationTree.scala, src/main/scala/io/citrine/lolo/trees/multitask/MultiTaskTrainingNode.scala, src/main/scala/io/citrine/lolo/trees/multitask/MultiTaskTree.scala, src/main/scala/io/citrine/lolo/trees/regression/RegressionTrainingNode.scala, src/main/scala/io/citrine/lolo/trees/regression/RegressionTree.scala, src/main/scala/io/citrine/lolo/trees/splits/ClassificationSplitter.scala, src/main/scala/io/citrine/lolo/trees/splits/MultiTaskSplitter.scala, src/main/scala/io/citrine/lolo/trees/splits/RegressionSplitter.scala, src/test/scala/io/citrine/lolo/learners/RandomForestTest.scala, src/test/scala/io/citrine/lolo/trees/regression/RegressionTreeTest.scala, src/test/scala/io/citrine/lolo/validation/CalibrationStudy.scala
The pivot is generally chosen to be the midpoint between the two nearest data points
in the split (i.e. the rightmost point in the left partition and the leftmost point in
the right partition).  If randomizePivotLocation is set, then the pivot location is
drawn uniformaly from the line between those two points.  This can improve
modeling performance and uncertainty quantification in ensemble models, e.g.
random forests.
=> Adding option to randomize pivot location in decision trees

src/main/scala/io/citrine/lolo/bags/BaggedResult.scala, src/main/scala/io/citrine/lolo/bags/Bagger.scala, src/test/scala/io/citrine/lolo/bags/BaggedResultTest.scala
There appears to be some inconsistency between single and multi-predict when jack-knife = false.
=> Add a failing case between single and multi predict

pom.xml, src/main/scala/io/citrine/lolo/bags/Bagger.scala, src/test/scala/io/citrine/lolo/bags/BaggerTest.scala
The calculation of the recalibration ratio takes into account points with zero uncertainty, and makes sure the resulting ratio is a real number.
=> Uncertainty recalibration

src/main/scala/io/citrine/lolo/bags/Bagger.scala, src/main/scala/io/citrine/lolo/transformers/Standardizer.scala, src/test/scala/io/citrine/lolo/bags/BaggerTest.scala
This bug was surfaced by Malcolm during the SLAC project.
=> Add failing test where RF fails to train when the response is constant

pom.xml, python/lolopy/version.py, src/main/scala/io/citrine/lolo/bags/Bagger.scala, src/main/scala/io/citrine/lolo/transformers/Standardizer.scala, src/test/scala/io/citrine/lolo/bags/BaggerTest.scala
If the response is constant, the standardizer won't try to rescale it to unit variance.
=> Release 2.2.4: bugfix where standardizer would produce nans when response was constant

python/Makefile, src/main/scala/io/citrine/lolo/bags/Bagger.scala, src/main/scala/io/citrine/lolo/trees/regression/RegressionTree.scala, src/test/scala/io/citrine/lolo/learners/RandomForestTest.scala
If we have small training data but draw lots of different
weight vectors, then one of them is likely to have all zero weights.
That will cause an empty training set and trigger an exception downstream.
This reproduces the error seen in #186 (I think).
=> Adding a test that fails because all the weights are zero

src/main/scala/io/citrine/lolo/bags/BaggedResult.scala, src/test/scala/io/citrine/lolo/bags/BaggerTest.scala
The variance is a sum of importance scores.  Each score is stochastic
and bias corrected, which is noisy and can result in scores that
are negative after the correction (which isn't possible).  We had
been rectifying each of those scores before summing them to get
the variance.
That wasn't a good idea: the whole point of the bias correction
is to shift the estimate down, but our rectifying logic was
in-introducing an upward bias.  Intead, we should rectify _after_
the sum, not before it.  If the result is still negative, then we'll
use the amplitude of the largest (or smallest) importance score
as an estimate of the variance scale.  However, in those cases, the user
should really be using more trees.
=> Be less aggresive about rectifying importance scores

src/main/scala/io/citrine/lolo/bags/BaggedResult.scala, src/main/scala/io/citrine/lolo/bags/Bagger.scala, src/main/scala/io/citrine/lolo/bags/MultiTaskBagger.scala, src/test/scala/io/citrine/lolo/bags/BaggedResultTest.scala, src/test/scala/io/citrine/lolo/bags/BaggerTest.scala
The MultiBaggedResult was riddled with if/else logic to handle both
regression and classification in the same class.  This was more confusing
than it was deduplicating, because we don't jackknife for classification.
This splits the classification result out explicitly, making it much
simpler and allowing the regression case to have the correct
T = Double generic class.
=> Refactor to split BaggedResult impls by type

src/main/scala/io/citrine/lolo/PredictionResult.scala, src/main/scala/io/citrine/lolo/transformers/FeatureRotator.scala, src/test/scala/io/citrine/lolo/transformers/FeatureRotatorTest.scala
This PR introduces a transformer that rotates input feature space before passing the transformed data to a base learner, with a specific aim of applying random rotations. There is reason to believe that random rotations of feature space can improve the performance of various kinds of learners --- such as by increasing entropy across an ensemble, or by decreasing the incidence of unimportant feature subsets for methods that use ensembles over random feature subsets. One promising application, random rotation ensembles introduced by Blaser & Fryzlewicz, trains each base learner in an ensemble method on a different random rotation of feature space; predictions are performed using the same rotations that were applied to the training data. Blaser & Fryzlewicz (2016) found large improvement in …
=> Support random rotations of features

python/lolopy/tests/test_learners.py, src/main/scala/io/citrine/lolo/PredictionResult.scala, src/main/scala/io/citrine/lolo/bags/BaggedResult.scala, src/main/scala/io/citrine/lolo/bags/Bagger.scala, src/main/scala/io/citrine/lolo/transformers/FeatureRotator.scala, src/main/scala/io/citrine/lolo/transformers/Standardizer.scala, src/main/scala/io/citrine/lolo/util/LoloPyDataLoader.scala, src/test/scala/io/citrine/lolo/util/LoloPyDataLoaderTest.scala, src/test/scala/io/citrine/lolo/validation/MeritTest.scala
This PR breaks out a specific `RegressionResult` interface and adds both the bias/variance/irreducible error decomposition and the prediction interval / confidence interval distinction.  Further, an `includeNoise` option is added to the existing `getUncertainty` method to distinguish between the prediction and confidence interval understandings of "uncertainty", e.g. "uncertainty in the expectation" vs "uncertainty of the outcome".  Finally, the interface is used for the bagger with ensemble variance serving as a prediction interval and the jackknife estimate as the variance.  The bias and confidence interval may be added pending further study.
=> Uncertainty decomposition in Regression Interface

src/main/scala/io/citrine/lolo/linear/GuessTheMean.scala, src/test/scala/io/citrine/lolo/learners/RandomForestTest.scala
Lolo classification forests using the default `GuessTheMeanLearner` do something that I find problematic when there are duplicated input rows in the training data. In particular, if `ClassificationTree` is trained on data in which the input `I` maps to both class labels `L1` and `L2` in equal proportion, only the label that appears first in the dataset passed to the leaf learner will affect that leaf's predictions. Although bagging should partially mitigate this effect, it will still bias predictions near `I` toward the categories that appear earlier in the training data whenever there are multiple data that have inputs `I` associated with different labels. This bug-report-as-test-case demonstrates this bias in the case of a classification forest.
=> Remove bias for duplicate input rows with different categorical labels.

README.md, pom.xml, python/lolopy/version.py
Deployed on Maven: https://search.maven.org/artifact/io.citrine/lolo/3.0.0/jar
Deployed on PyPi: https://pypi.org/project/lolopy/1.1.0/
=> Bump to version 3.0.0

README.md, RELEASE.md
* Fix version number in README.md
* Add RELEASE.md
Still should work on clarifying docs related to https://github.com/CitrineInformatics/lolo/blob/0f641bdea4a5b67de44f43001097079a90911676/src/main/scala/io/citrine/lolo/PredictionResult.scala#L52 but that will need a rep of conversation.
Release notes:
Lolo version 3.0.0 is released! Notably, this release introduces a shiny new interface for uncertainty quantification that provides new and improved granular uncertainty quantification (UQ). This release also introduces two new random forest features, and improves the accuracy of predictions and UQ on certain types of machine learning problems.
* Now you can distinguish estimated uncertainty in observations from uncertainty in the mean! You can query each of these with a new interface that …
=> Release/3.0.0 touch-up

src/main/scala/io/citrine/lolo/bags/BaggedResult.scala, src/main/scala/io/citrine/lolo/bags/BaggerUtil.scala, src/main/scala/io/citrine/lolo/bags/MultiTaskBagger.scala, src/test/scala/io/citrine/lolo/bags/BaggedResultTest.scala, src/test/scala/io/citrine/lolo/bags/MultiTaskBaggerTest.scala
* Check `observational` parameter of `getUncertainty`
* Make `getStdDevMean` a standard deviation instead of a variance
* Nudge `MultiTaskBagger` UQ interface toward that of `Bagger`.
* Add `BaggerUtil` so functionality common to `Bagger` and `MultiTaskBagger` can be maintained in one place. (Currently used only by `MultiTaskBagger`, and a subsequent PR will swing over functionality from `Bagger`.)
Note that the second two items, while important, started with a wild goose chase because of nondeterministic tests (see https://github.com/CitrineInformatics/lolo/issues/206)
=> Fix uncertainty interface mixup

src/main/scala/io/citrine/lolo/bags/BaggedResult.scala, src/main/scala/io/citrine/lolo/bags/Bagger.scala, src/main/scala/io/citrine/lolo/bags/BaggerUtil.scala, src/test/scala/io/citrine/lolo/bags/BaggedResultTest.scala, src/test/scala/io/citrine/lolo/bags/MultiTaskBaggerTest.scala
This PR adds a sanity check on reported standard deviations for regression, and re-applies the conversion to using the rescaled bootstrap ensemble for predictive uncertainty and jackknife for standard error. This PR is a step toward fixing https://github.com/CitrineInformatics/lolo/issues/207 and also implements the Bessel correction (https://github.com/CitrineInformatics/lolo/issues/213).
=> UQ sanity check

project/Dependencies.scala, src/main/scala/io/citrine/lolo/bags/MultiTaskBagger.scala
Removing scalactic library from lolo as it is not being used. This transitive dependency is being pulled into the platform-backend causing a version clash.
=> Removing scalactic

.travis.yml, python/Makefile, src/main/scala/io/citrine/lolo/encoders/CategoricalEncoder.scala, src/test/scala/io/citrine/lolo/encoders/CategoricalEncoderTest.scala
Use `.map` instead of `.mapValues` to make `decoding` field in `CategoricalEncoder` serializable.
Fixes #237
=> Make `CategoricalEncoder` serializable

.travis.yml, README.md
Simplify the branching pattern from gitflow to feature branch flow,
base it on main instead of master, and otherwise update the readme a
bit.
=> Update master -> main; describe tag releases; contributors

src/main/scala/io/citrine/lolo/trees/splits/Split.scala, src/test/scala/io/citrine/lolo/trees/splits/SplitTest.scala
Since 0 < NaN is false but also 0 >= NaN is false, NaN pivots
were putting everything into the same split, which was breaking
an assertion later in the code.  This checks to see if the pivot
is NaN and, if so, splits on `isNaN`.
=> Split NaN and non-NaN values in RealSplit

.travis.yml, python/Makefile
We added sbt-launch-repo to deal with a sbt hosting migration.
Now that's over, and we shouldn't need it anymore, which is good
because it is not part of standard SBT
=> Remove sbt-launch-repo, which was a hack and isn't standard

src/main/scala/io/citrine/lolo/bags/BaggedResult.scala, src/main/scala/io/citrine/lolo/bags/CorrelationMethods.scala, src/main/scala/io/citrine/lolo/bags/MultiTaskBagger.scala, src/main/scala/io/citrine/lolo/stats/StatsUtils.scala, src/main/scala/io/citrine/lolo/stats/utils.scala, src/test/scala/io/citrine/lolo/bags/MultiTaskBaggerTest.scala, src/test/scala/io/citrine/lolo/stats/UtilsTest.scala
This PR implements several ways of calculating the uncertainty correlation for a multitask bagged model. Assuming the two labels are distinct and both correspond to real values, then we have the following options:
* always predict rho = 0 (this is the trivial method)
* calculate rho using the correlation over training data
* calculate rho using the bootstrap predictions
* calculate rho from the infinitesimal jackknife & jackknife-after-bootstrap covariance, divided by the square root of the associated variances
The last method is implemented in two different ways. One is more explicit and uses loops. It can be easily compared to the published method in Wager et. al. (2014). The other is more performant and uses matrix arithmetic. The two are tested against each other for consistency.
=> Pla 8537/implement several correlations

src/main/scala/io/citrine/lolo/TrainingResult.scala, src/main/scala/io/citrine/lolo/bags/Bagger.scala, src/main/scala/io/citrine/lolo/bags/MultiTaskBagger.scala, src/main/scala/io/citrine/lolo/stats/metrics/ClassificationMetrics.scala, src/main/scala/io/citrine/lolo/stats/metrics/RegressionMetrics.scala, src/main/scala/io/citrine/lolo/transformers/FeatureRotator.scala, src/main/scala/io/citrine/lolo/transformers/Standardizer.scala, src/test/scala/io/citrine/lolo/bags/MultiTaskBaggerTest.scala
Implement `getPredictedVsActual` for multitask bagged model, and in doing so allow for an implementation of `getLoss`. Because we expect to use multitask bagged models inside of a standardizer model, we also implement `getPredictedVsActual` for standardizers.
=> Pla 8566/multitask predicted-vs-actual

src/main/scala/io/citrine/lolo/bags/BaggedResult.scala
As part of using the jackknife approach to calculate covariance, it is possible that the noisy bias correction term leads to an unphysical result. Specifically, it can predict a correlation coefficient (rho) that is < -1 or > 1, both of which are nonsensical and cause numerical issues (we cannot draw from the resulting distribution). This is similar to how the estimates of variance can yield a negative number because of sampling noise, which we solve through a [heuristic rectification procedure](https://github.com/CitrineInformatics/lolo/blob/PLA-8597/rectify-noisy-covariance/src/main/scala/io/citrine/lolo/bags/BaggedResult.scala#L672).
I studied 4 ways to resolve this issue.
1. If rho is outside of the allowed range*, set it to the edge of that range
2. If rho is outside of the allowed …
=> Rectify noisy covariance

src/main/scala/io/citrine/lolo/Learner.scala, src/main/scala/io/citrine/lolo/bags/BaggedResult.scala, src/main/scala/io/citrine/lolo/bags/MultiTaskBagger.scala, src/main/scala/io/citrine/lolo/transformers/FeatureRotator.scala, src/main/scala/io/citrine/lolo/transformers/Standardizer.scala, src/main/scala/io/citrine/lolo/trees/multitask/MultiTaskTree.scala, src/test/scala/io/citrine/lolo/PerformanceTest.scala, src/test/scala/io/citrine/lolo/bags/MultiTaskBaggerTest.scala, src/test/scala/io/citrine/lolo/transformers/FeatureRotatorTest.scala, src/test/scala/io/citrine/lolo/transformers/StandardizerTest.scala, src/test/scala/io/citrine/lolo/trees/multitask/MultiTaskTreeTest.scala
PLA-8798
`Learner` implements a method `train` that acts on a sequence of training data points, each of the form `(vector of inputs, label)`. But `MultiTaskLearner` implements `train` with a different interface: it takes one argument for the `inputs` and one argument for the `labels`. To make matters more confusing, the two arguments have different orientations. `inputs` has shape `(# training) x (# input dimensions)` while `labels` has shape `(# output dimensions) x (# training)`. This was undocumented and, at least to me, counter-intuitive.
In the context of Lolo it's not a big deal. But when I tried to implement the multi-task RF in Lolopy, I found that having these two different paradigms would lead to a lot of boilerplate, redundant code. So I decided to unify the interfaces, since …
=> Unify learner train interface

.travis.yml, python/README.md, python/lolopy/learners.py, python/lolopy/tests/test_learners.py, python/requirements.txt, src/main/scala/io/citrine/lolo/bags/BaggedResult.scala, src/main/scala/io/citrine/lolo/learners/ExtraRandomTrees.scala, src/main/scala/io/citrine/lolo/learners/RandomForest.scala, src/main/scala/io/citrine/lolo/trees/multitask/MultiTaskTrainingNode.scala, src/main/scala/io/citrine/lolo/trees/multitask/MultiTaskTree.scala, src/main/scala/io/citrine/lolo/trees/regression/RegressionTree.scala, src/main/scala/io/citrine/lolo/trees/splits/MultiTaskSplitter.scala, src/main/scala/io/citrine/lolo/util/LoloPyDataLoader.scala, src/test/scala/io/citrine/lolo/learners/RandomForestTest.scala
PLA-8731
Makes it so that the `RandomForestRegressor` model in Lolopy can be trained on 2-dimensional label data, `y`. The model then returns predictions as a 2-dimensional array. This brings its behavior more in line with scikit-learn's random forest regressor, which can also operate on multiple labels. The following changes were made to enable this feature:
* The `RandomForest` learner in Lolo now checks to see if the output data is a `Seq` (previously it only checked whether or not it was a `Double`). If it's a `Seq`, then it produces a `MultiTaskBagger` around a standardized `MultiTaskTreeLearner`.
* The top-level `fit` method of `BaseLoloLearner` inspects the shape of the training labels `y`, and if it's a 2-d array then it gets sent to Java as an array instead of as a vector
* The …
=> Expose multitask random forest in Lolopy

src/main/scala/io/citrine/lolo/learners/RandomForest.scala, src/test/scala/io/citrine/lolo/learners/RandomForestTest.scala
When training a typical random forest model, there are two primary sources of randomness: bagging and selecting features to consider at each split. Previously we did not pass the `rng` to the splitter, so the latter was not reproducible. This PR fixes that.
=> Pass rng to splitters in RandomForest

build.sbt
In [this Sonatype support request](https://issues.sonatype.org/browse/OSSRH-76297) we migrated Lolo and Theta to be published under the new Sonatype infrastructure. This PR configures the sbt ci-release plugin to use the new infrastructure url.
NB: This is my first time editing sbt config and I have no idea what I'm doing. Changes seem pretty straightforward but please double check I'm not making some beginner mistake.
=> Publish to new sonatype infrastructure

src/main/scala/io/citrine/lolo/bags/Bagger.scala, src/main/scala/io/citrine/lolo/bags/BaggerUtil.scala, src/main/scala/io/citrine/lolo/bags/MultiTaskBagger.scala, src/main/scala/io/citrine/lolo/learners/RandomForest.scala
Sets `uncertaintyCalibration` to have a default value of true for `RandomForest`, `Bagger`, and `MultiTaskBagger`*. This is because the default uncertainty for the resulting predictions is observational uncertainty, which makes the most sense as a recalibrated bootstrap standard deviation, but that recalibration is not done if `uncertaintyCalibration = false`. Therefore, our defaults led to nonintuitive behavior.
The rescale ratio can sometimes be Infinity if the number of training data and bags are small. Since we have two tests that run thousands of trials and check that sigma is positive, now that `uncertaintyCalibration` is true it sometimes runs into that situation and throws an error. I have made is so that `ratio` is set to 1.0 in this scenario.
Since I was changing the rescale …
=> Uncertainty calibration default true

src/main/scala/io/citrine/lolo/validation/Merit.scala, src/test/scala/io/citrine/lolo/validation/CalibrationStudy.scala, src/test/scala/io/citrine/lolo/validation/MeritTest.scala
For `StandardConfidence`, `StandardError`, and `UncertaintyCorrelation`, allow the calling code to specify whether the uncertainties should be observational or not (default is observational).
=> Allow observational option for more Merits

src/main/scala/io/citrine/lolo/bags/Bagger.scala
These are useful for examining the out-of-bag predictions in benchmarking
=> expose NiB and models in BaggedModel

src/main/scala/io/citrine/lolo/bags/Bagger.scala, src/test/scala/io/citrine/lolo/bags/BaggerTest.scala
Minor bugfix to return `None` if the ensemble doesn't return Shapley values.
=> Return None if ensemble doesn't return Shapley values.

.travis.yml, python/README.md, python/setup.py
I was able to figure out why the PyPi release stage of my recent jobs were failing. `pypandoc` released a new version, which [removed the deprecated method `pypandoc.convert` that we were calling](https://github.com/NicklasTegner/pypandoc/pull/257).
As it turns out, we no longer need to use this package. `pypandoc` is used to convert a `.md` file to an `.rst` file, which was previously being used to convert out README to a PyPi display format. As of March 2018 PyPi can natively accept `.md` files in the description, so we no longer need a conversion (see notes [here](https://stackoverflow.com/questions/26737222/how-to-make-pypi-description-markdown-work), and `pyspark` example setup file [here](https://github.com/apache/spark/blob/master/python/setup.py)). I have updated the Python setup …
=> Update PyPi docs during Python release

src/main/scala/io/citrine/lolo/bags/Bagger.scala, src/main/scala/io/citrine/lolo/bags/BaggerUtil.scala, src/main/scala/io/citrine/lolo/bags/MultiTaskBagger.scala, src/test/scala/io/citrine/lolo/bags/MultiTaskBaggerTest.scala
In order to allow running SL simulations using a variety of confidence level parameters, we expose an uncertainty level parameter. Instead of specifying whether they want to do uncertainty recalibration using a Boolean, users can specify the level of `p` (between 0 and 1).
This option is only exposed in `MultiTaskBagger`. In `Bagger`, a value of `true` maps to 0.683.
=> Configure recalibration for multitask bagger

src/main/scala/io/citrine/lolo/linear/GuessTheMean.scala, src/test/scala/io/citrine/lolo/linear/GuessTheMeanTest.scala
The `GuessTheMeanLearner` exhibits roundoff error when the training data are identical. This can be an issue when the training data value in question is extremal and coupled with a `Standardizer`. The roundoff error can push the resulting prediction out of bounds.
=> Fix roundoff error in GTM learner

src/main/scala/io/citrine/lolo/transformers/standardizer/StandardizerModel.scala, src/test/scala/io/citrine/lolo/transformers/standardizer/StandardizerTest.scala
Fixes a bug in which `RegressionStandardizerModel`s did not call the shapley correctly. Added an override shapley method to `RegressionStandardizerModel` so that the models call the shapley method based on the base model type instead of the generic `Model[T].shapley()` which always returns None.
=> PNE 363 Emit Shapley Values

src/main/scala/io/citrine/lolo/trees/ModelNode.scala, src/main/scala/io/citrine/lolo/trees/classification/ClassificationTree.scala, src/test/scala/io/citrine/lolo/trees/classification/ClassificationTreeTest.scala, src/test/scala/io/citrine/lolo/trees/multitask/MultiTaskTreeTest.scala
Extends Shapley to `MultiTaskTree` and `ClassificationTree` models. For the `MultiTaskTree` models Shapley Values are returned for each individual task label (e.g. if model predicts y_1 and y_2, we obtain separate Shapley values for y_1 and y_2). `ClassificationTree` models follow the same implementation as regression trees but are based on numeric class labels.
=> Pne 424 multitask classification shapley

.github/workflows/deployPyPi.yml, src/main/scala/io/citrine/lolo/trees/ModelNode.scala
This change adds a `@transient lazy private val` decorator to the `leftPortion` and `rightPortion` in `ModelNode`. This keeps us from serializing the portions which will break SerDe
=> Pne 6240 add transient decorator to shapley

.github/workflows/deploy.yml, .github/workflows/tests.yml, src/main/scala/io/citrine/lolo/transformers/standardizer/StandardizerModel.scala, src/test/scala/io/citrine/lolo/transformers/standardizer/StandardizerTest.scala, src/test/scala/io/citrine/lolo/trees/regression/RegressionTreeTest.scala
Currently in our standardized models the inputs and outputs are not handled properly for shapley calculations. We need to standardize input for shapley so that the inputs are correctly scaled to what the model is actually trained on. We also need to  invert the standardization of the final shapley values so the scale is the same as the target values.
=> PNE-6481/shapley-standardization

python/lolopy/learners.py, python/lolopy/version.py, python/requirements.txt
With the Tag abstraction introduced in scikit-learn 1.6, method resolution order grabs the tags from [BaseEstimator](https://github.com/scikit-learn/scikit-learn/blob/d8932866b6f4b2dee508a54b79f1122ff5f5459d/sklearn/base.py#L421) instead of [RegressorMixin](https://github.com/scikit-learn/scikit-learn/blob/d8932866b6f4b2dee508a54b79f1122ff5f5459d/sklearn/base.py#L614), resulting in a py4j casting error on targets.
=> Update mixin order per scikit-learn 1.6 release

.github/workflows/tests.yml, python/lolopy/version.py, python/requirements.txt, python/setup.py, python/tests/test_learners.py, python/tests/test_metrics.py
Updates the actions testing to include a range of python versions and to test 3.12 on a range of os's.  Also updates requirements to match the actual range of Python versions.
=> Update testing to use os / version matrix

.github/workflows/deploy.yml, .github/workflows/deployPyPi.yml, .github/workflows/tests.yml, python/lolopy/version.py
This modifies both publish actions so that they only run when we manually trigger a release.
This also homogenizes the various actions so that dependencies between the various actions are consistent.
=> Modify publish actions so publishing happens upon releases
